# Generated by Django 3.2.7 on 2024-05-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depression_detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer',
            new_name='patient_tbl',
        ),
    ]
