# Generated by Django 3.2.7 on 2024-05-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depression_detection', '0002_rename_customer_patient_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='psychiatrist_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('specialization', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('clinic_name', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('timing', models.CharField(max_length=120)),
                ('place', models.CharField(max_length=120)),
                ('year_of_experience', models.CharField(max_length=120)),
            ],
        ),
    ]
