# Generated by Django 3.2.7 on 2024-05-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depression_detection', '0004_guestuser_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultation_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=150)),
                ('documents', models.CharField(max_length=120)),
                ('medicines', models.CharField(max_length=120)),
                ('prescription', models.CharField(max_length=120)),
            ],
        ),
    ]
