# Generated by Django 3.2.7 on 2024-05-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depression_detection', '0006_feedback_tbl_payment_tbl_result_tbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation_tbl',
            name='user_id',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
