# Generated by Django 3.2.12 on 2024-06-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depression_detection', '0007_consultation_tbl_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation_tbl',
            name='clinic_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation_tbl',
            name='timing',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
