# Generated by Django 3.2.12 on 2024-06-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depression_detection', '0009_result_tbl_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation_tbl',
            name='amount',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
