# Generated by Django 3.2.12 on 2024-06-07 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depression_detection', '0010_consultation_tbl_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation_tbl',
            name='amount',
        ),
    ]
