# Generated by Django 3.2.12 on 2024-06-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depression_detection', '0011_remove_consultation_tbl_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='fee_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=150)),
                ('user_id', models.CharField(max_length=120)),
                ('amount', models.CharField(max_length=120)),
                ('clinic_name', models.CharField(max_length=120)),
            ],
        ),
    ]
