# Generated by Django 3.2.12 on 2024-06-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depression_detection', '0012_fee_tbl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_tbl',
            old_name='userid',
            new_name='card_no',
        ),
        migrations.AddField(
            model_name='payment_tbl',
            name='card_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_tbl',
            name='clinic_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_tbl',
            name='cvv',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_tbl',
            name='user_id',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment_tbl',
            name='did',
            field=models.CharField(max_length=150),
        ),
    ]
