# Generated by Django 3.2.7 on 2024-07-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depression_detection', '0014_result_tbl_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='med_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=120)),
                ('notes', models.CharField(max_length=120)),
            ],
        ),
    ]
