# Generated by Django 3.2.7 on 2024-07-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depression_detection', '0015_med_tbl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='med_tbl',
            old_name='description',
            new_name='timingss',
        ),
        migrations.AddField(
            model_name='consultation_tbl',
            name='notes',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation_tbl',
            name='timingss',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
